name: Keep Render & Supabase Alive

on:
  schedule:
    # Every hour between 7 a.m. and 7 p.m. UTC+1 (Nigeria time)
    - cron: "0 6-18 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /health endpoint
        run: |
          for i in {1..5}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://url-shortener-service-7vhn.onrender.com/health)
            echo "Attempt $i - Status: $STATUS"
            if [ "$STATUS" -eq 200 ]; then
              echo "✅ Service is awake"
              exit 0
            fi
            echo "Service still sleeping... retrying in 20s"
            sleep 20
          done
          echo "❌ Failed to wake service after retries"
          exit 1
